# Generated by Django 4.0.2 on 2022-03-17 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0002_remove_ingredient_quantity_remove_ingredient_recipes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='parent',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='wom.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name='Date Published'),
        ),
    ]
