# Generated by Django 4.0.2 on 2022-03-22 16:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0003_alter_recipe_course_alter_recipe_meal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wom.recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='units',
            field=models.CharField(default='oz', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published'),
        ),
        migrations.DeleteModel(
            name='IngredientQuantity',
        ),
    ]
