# Generated by Django 4.0.2 on 2022-03-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0004_ingredient_quantity_ingredient_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='creator',
            field=models.CharField(default='Anonymous cook', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
