# Generated by Django 4.0.2 on 2022-03-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0005_recipe_creator_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='creator',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
