# Generated by Django 4.0.2 on 2022-03-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0003_recipe_parent_alter_ingredientquantity_units_and_more'),
        ('wom', '0006_alter_recipe_creator'),
    ]

    operations = [
    ]
