# Generated by Django 4.0.2 on 2022-03-26 20:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0009_remove_ingredient_quantity_remove_ingredient_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 26, 20, 57, 3, 668499, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
