# Generated by Django 4.0.2 on 2022-03-26 22:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0011_alter_recipe_cooking_time_alter_recipe_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 26, 22, 38, 51, 312959, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
