# Generated by Django 4.0.2 on 2022-03-26 23:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0013_alter_recipe_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 26, 23, 9, 6, 715258, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
