# Generated by Django 4.0.2 on 2022-03-27 09:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0011_alter_recipe_cooking_time_alter_recipe_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='wom.recipe'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='units',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='course',
            field=models.CharField(choices=[('other', 'Other'), ('appetizer', 'Appetizer'), (
                'entree', 'Entree'), ('side', 'Side'), ('snack', 'Snack')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('other', 'Other'), ('breakfast', 'Breakfast'), (
                'lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert')], default='other', max_length=10),
        ),
        migrations.DeleteModel(
            name='IngredientQuantity',
        ),
    ]
