# Generated by Django 3.2.12 on 2022-03-27 20:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0025_alter_ingredient_quantity_alter_recipe_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 20, 30, 32, 589815, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
