# Generated by Django 4.0.2 on 2022-03-30 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0008_alter_recipe_creator_alter_recipe_parent'),
        ('wom', '0026_alter_recipe_pub_date'),
    ]

    operations = [
    ]
