# Generated by Django 4.0.2 on 2022-03-31 19:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0027_alter_recipe_pub_date_raterecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriterecipe',
            name='fav_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 19, 48, 25, 464793, tzinfo=utc), verbose_name='Date Favorited'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 19, 48, 25, 464793, tzinfo=utc), verbose_name='Date Published'),
        ),
    ]
