# Generated by Django 4.0.2 on 2022-03-31 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0028_alter_favoriterecipe_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='creator',
            field=models.CharField(default='fd', max_length=100),
            preserve_default=False,
        ),
    ]
