# Generated by Django 4.0.2 on 2022-04-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0029_alter_recipe_pub_date'),
        ('wom', '0031_alter_favoriterecipe_recipe'),
    ]

    operations = [
    ]
