# Generated by Django 4.0.2 on 2022-04-10 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0028_recipe_anonymous_creator_bool_alter_recipe_pub_date'),
        ('wom', '0034_tag'),
    ]

    operations = [
    ]
