# Generated by Django 3.2.12 on 2022-04-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0034_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.FileField(default='https://wom-photo.s3.amazonaws.com/no-image.jpg', upload_to=''),
        ),
    ]
