# Generated by Django 4.0.2 on 2022-04-07 20:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0034_recipe_numratings_alter_favoriterecipe_fav_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='avgScore',
            new_name='avgRating',
        ),
        migrations.AlterField(
            model_name='favoriterecipe',
            name='fav_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 20, 38, 12, 25828, tzinfo=utc), verbose_name='Date Favorited'),
        ),
    ]
