# Generated by Django 4.0.2 on 2022-04-09 17:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0035_rename_avgscore_recipe_avgrating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipe',
            name='fav_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 17, 41, 50, 644036, tzinfo=utc), verbose_name='Date Favorited'),
        ),
    ]
