# Generated by Django 3.2.12 on 2022-04-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0035_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
