# Generated by Django 4.0.2 on 2022-04-09 18:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0036_alter_favoriterecipe_fav_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipe',
            name='fav_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 18, 10, 10, 614387, tzinfo=utc), verbose_name='Date Favorited'),
        ),
    ]
