# Generated by Django 4.0.2 on 2022-04-10 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0037_alter_favoriterecipe_fav_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipe',
            name='fav_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Favorited'),
        ),
    ]
