# Generated by Django 4.0.2 on 2022-04-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0035_merge_20220410_1427'),
        ('wom', '0038_alter_favoriterecipe_fav_date'),
    ]

    operations = [
    ]
