# Generated by Django 3.2.12 on 2022-04-12 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0027_alter_recipe_pub_date_raterecipe'),
        ('wom', '0040_alter_recipe_pub_date'),
        ('wom', '0041_recipe_image'),
    ]

    operations = [
    ]
