# Generated by Django 4.0.2 on 2022-04-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0043_alter_recipe_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
