# Generated by Django 4.0.2 on 2022-04-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0044_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
