# Generated by Django 4.0.2 on 2022-05-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wom', '0045_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='units',
            field=models.CharField(max_length=10),
        ),
    ]
